export const servicesMock = [
  {
    id: 1,
    titulo: 'Consulta de Enfermagem',
    descricao: 'Acompanhamento individualizado com avaliação completa, orientações personalizadas e plano de cuidados exclusivo.',
    imagem: '/images/services/consultaenf2.jpg',
    link: '/servicos/consulta-de-enfermagem',
  },
  {
    id: 2,
    titulo: 'Procedimentos de Enfermagem',
    descricao: 'Realizamos todos os procedimentos de enfermagem com segurança, ética e competência.',
    imagem: '/images/services/procenfatual.jpg',
    link: '/servicos/procedimentos-de-enfermagem',
  },
  {
    id: 3,
    titulo: 'Administração de Medicamentos',
    descricao: 'Administração segura e responsável de medicamentos por via oral, injetável, subcutânea, intravenosa e outras.',
    imagem: '/images/backgrounds/banner1.jpeg',
    link: '/servicos/adminstracao-de-medicamentos',
  },
  {
    id: 4,
    titulo: 'Tratamento de Lesões',
    descricao: 'Especialidade em tratamento de lesões de difícil cicatrização com recursos modernos e eficazes.',
    imagem: '/images/services/procenf.jpg',
    link: '/servicos/tratamento-de-lesoes',
  },
  {
    id: 5,
    titulo: 'Atendimento Domiciliar',
    descricao: 'Cuidados especializados no conforto do seu lar, com toda a segurança e profissionalismo.',
    imagem: '/images/services/medpordomici.jpg',
    link: '/servicos/atendimento-domiciliar',
  },
  {
    id: 6,
    titulo: 'Teleconsulta',
    descricao: 'Consultas de enfermagem online com toda a comodidade e segurança, sem sair de casa.',
    imagem: '/images/services/teleconsulta.jpg',
    link: '/servicos/teleconsulta',
  },
  {
    id: 7,
    titulo: 'Atendimento Capilar',
    descricao: 'Cuidados especializados para o couro cabeludo e cabelos, com tratamentos personalizados.',
    imagem: '/images/services/atendimentocapilar.jpg',
    link: '/servicos/atendimento-capilar',
  },
  {
    id: 8,
    titulo: 'Laserterapia',
    descricao: 'Tratamento avançado com laser para lesões, feridas e problemas de pele com tecnologia de ponta.',
    imagem: '/images/services/grasi2.jpg',
    link: '/servicos/laserterapia',
  },
  {
    id: 9,
    titulo: 'RC Educação',
    descricao: 'Cursos e treinamentos especializados em enfermagem com metodologia dinâmica e professores experientes.',
    imagem: '/images/services/cursosetreinamentos.jpg',
    link: '/servicos/rc-educacao',
  }
];